on:
  youtube:
    playlist_id: PLHYpJBpUneguwI1mPWocqBZGjovn-pj0u
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.youtube.outputs.title}}
          videoId: ${{on.youtube.outputs.videoId}}
        run: |
          echo title: $title
          echo videoId: $videoId
